In [36]:
#warnings
import warnings
warnings.filterwarnings('ignore')

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
import numpy as np
import pandas as pd

# data visuzlization
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st

In [39]:
# max columns
pd.set_option('display.max_columns', None)
# max rows
pd.set_option('display.max_rows', None)

In [40]:
df = pd.read_csv('/content/drive/My Drive/Project/Project 5/MODELS/Bonik/diabetic_data.csv')
df.replace('?',np.nan,inplace=True)
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [41]:
df.shape

(101766, 50)

In [42]:
m=pd.DataFrame({'Number of Missing':df.isnull().sum() , 'Missing Percentage':np.round(df.isnull().sum()*100/len(df),1)})
m=m[m['Missing Percentage']>0]
m

                   Number of Missing  Missing Percentage
race                            2273                 2.2
weight                         98569                96.9
payer_code                     40256                39.6
medical_specialty              49949                49.1
diag_2                           358                 0.4
diag_3                          1423                 1.4

In [43]:
#dropping columns with high NA percentage
df.drop(['weight','medical_specialty','payer_code'],axis=1,inplace=True)
# dropping columns related to IDs
df.drop(['encounter_id','patient_nbr','admission_type_id',
         'discharge_disposition_id','admission_source_id'],axis=1,inplace=True)
#removing invalid/unknown entries for gender
df=df[df['gender']!='Unknown/Invalid']

In [44]:
# dropping rows with NAs.
df.dropna(inplace=True)

In [45]:
df.head()

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
1,Caucasian,Female,[10-20),3,59,0,18,0,0,0,276,250.01,255,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,[20-30),2,11,5,13,2,0,1,648,250,V27,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,[30-40),2,44,1,16,0,0,0,8,250.43,403,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,Caucasian,Male,[40-50),1,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,Caucasian,Male,[50-60),3,31,6,16,0,0,0,414,411,250,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30

In [46]:
diag_cols = ['diag_1','diag_2','diag_3']
for col in diag_cols:
    df[col] = df[col].str.replace('E','-')
    df[col] = df[col].str.replace('V','-')
    condition = df[col].str.contains('250')
    #print(condition)
    df.loc[condition,col] = '250'
    #print(df.loc[condition,col])
    print(df[col].value_counts().T)

250     7965
428     6730
414     6373
786     3900
410     3514
486     3412
427     2701
491     2210
715     2073
434     1983
780     1976
682     1966
996     1926
276     1831
38      1642
599     1557
584     1496
-57     1179
518     1092
820     1034
577     1017
493     1010
435      987
562      957
574      937
560      850
296      842
440      817
433      768
998      752
722      703
578      643
507      595
789      545
453      530
530      521
8        500
403      497
535      445
402      445
415      436
295      428
162      419
458      418
724      417
997      414
285      362
733      352
278      343
401      336
592      332
482      331
558      330
590      326
197      314
280      311
153      305
824      300
569      281
426      278
571      269
531      268
511      264
787      259
404      258
648      255
707      250
411      238
198      236
572      235
466      232
552      226
-58      223
730      222
812      220
532      213
575      210
600      196
557      191
331      190
805      175
424      174
431      171
721      170
540      170
436      166
618      155
444      152
185      151
348      149
536      149
784      146
564      143
174      142
790      140
821      140
386      139
553      137
808      128
728      126
823      124
398      124
441      122
515      122
218      122
189      120
413      113
294      113
157      112
681      110
537      108
345      107
188      105
729      105
443      105
182      104
852      103
292      103
781      101
785      100
593      100
211       99
202       99
487       95
576       94
274       93
595       93
154       93
459       93
455       92
288       92
654       91
432       91
726       88
291       87
290       86
437       86
490       85
287       85
300       84
438       82
425       82
782       81
79        80
346       80
626       79
995       77
723       77
813       76
566       75
807       75
112       73
585       73
423       70
-55       69
496       69
481       68
799       67
608       66
416       66
711       64
298       63
303       63
420       62
282       61
238       61
284       61
447       60
642       60
625       59
969       58
151       58
567       57
293       55
738       55
241       55
962       54
311       54
53        54
275       53
716       53
719       53
155       53
550       53
924       52
965       52
850       52
332       51
555       50
465       48
253       48
596       47
512       46
822       46
9         45
620       45
220       45
727       45
286       44
227       44
556       44
191       44
70        44
340       43
519       43
42        43
-53       43
959       42
514       42
225       41
485       41
421       40
573       40
714       40
-54       40
922       39
451       37
604       36
860       36
788       36
203       35
333       35
429       35
442       34
516       34
309       33
851       33
611       33
239       33
277       32
659       32
568       32
492       32
349       32
510       31
183       31
304       30
351       30
802       30
801       30
783       29
430       29
844       27
233       27
205       27
193       27
999       27
47        26
644       26
235       26
527       26
658       26
135       26
794       26
478       26
196       25
283       25
661       25
710       25
396       25
150       24
522       24
534       24
456       24
494       23
825       23
252       23
255       23
327       23
305       22
473       22
533       22
621       22
307       22
446       21
242       21
614       21
204       21
693       21
656       21
920       21
616       21
586       21
461       20
607       20
357       20
338       20
281       20
528       19
664       19
581       19
617       19
591       19
958       19
156       18
289       18
627       18
312       18
873       17
972       17
718       17
380       17
967       17
480       17
200       16
601       16
226       16
853       16
-56       16
355       16
152       15
513       15
756       15
199       14
378       14
652       13
840       13
358       13
935       13
594       13
3         13
251       13
861       13
933       13
736       13
867       13
263       12
171       12
847       12
475       12
966       12
297       12
680       12
565       12
843       12
977       12
457       12
376       12
660       12
462       11
394       11
725       11
244       11
368       11
158       11
310       11
695       11
989       11
945       11
882       10
337       10
891       10
892       10
350       10
306       10
54        10
161       10
705       10
11        10
323       10
521       10
646       10
201       10
35        10
464       10
5          9
335        9
810        9
454        9
816        9
-71        9
845        9
952        9
588        9
383        9
184        9
88         9
230        9
195        9
78         9
992        9
354        8
359        8
41         8
709        8
686        8
641        8
362        8
970        8
163        8
964        8
212        8
117        8
551        8
968        8
342        8
541        8
-63        8
82         7
237        7
745        7
815        7
747        7
991        7
708        7
341        7
746        7
663        7
831        7
737        7
223        7
320        7
717        7
866        7
445        7
579        7
864        7
94         7
141        6
344        6
865        6
570        6
694        6
214        6
353        6
806        6
273        6
696        6
324        6
883        6
66         6
796        6
34         6
836        6
526        6
180        6
175        5
495        5
356        5
395        5
814        5
215        5
619        5
583        5
643        5
210        5
751        5
692        5
228        5
452        5
361        5
49         5
208        5
835        5
942        5
647        5
397        5
881        5
983        5
598        5
379        5
685        5
508        5
893        5
753        5
483        5
854        5
136        5
934        5
886        4
846        4
890        4
172        4
923        4
792        4
720        4
655        4
301        4
674        4
793        4
623        4
192        4
863        4
463        4
622        4
261        4
146        4
142        4
759        4
916        4
388        4
272        4
734        4
731        4
-45        4
800        4
524        4
245        4
529        4
470        4
474        3
506        3
706        3
862        3
669        3
602        3
803        3
31         3
405        3
374        3
179        3
868        3
917        3
928        3
665        3
795        3
266        3
262        3
986        3
963        3
370        3
173        3
632        3
336        3
971        3
164        3
240        3
797        3
936        3
987        3
826        3
377        3
271        3
39         2
610        2
279        2
360        2
703        2
634        2
875        2
236        2
382        2
308        2
422        2
246        2
975        2
322        2
683        2
990        2
149        2
921        2
58         2
914        2
369        2
580        2
27         2
194        2
941        2
7          2
110        2
187        2
334        2
-66        2
352        2
229        2
131        2
980        2
582        2
904        2
170        2
653        2
36         2
879        2
384        2
48         2
115        2
23         2
500        2
615        2
657        2
147        2
732        2
501        2
880        2
417        2
878        2
944        2
848        2
645        2
735        2
973        2
897        2
633        2
75         2
207        1
160        1
216        1
834        1
994        1
314        1
391        1
832        1
98         1
217        1
871        1
955        1
791        1
299        1
913        1
-67        1
640        1
-51        1
974        1
839        1
61         1
895        1
114        1
325        1
690        1
373        1
684        1
804        1
381        1
477        1
915        1
976        1
523        1
-60        1
-07        1
700        1
603        1
52         1
-25        1
347        1
957        1
363        1
637        1
837        1
366        1
698        1
827        1
649        1
982        1
842        1
838        1
385        1
365        1
57         1
-909       1
911        1
906        1
448        1
939        1
133        1
372        1
318        1
389        1
542        1
375        1
870        1
988        1
833        1
412        1
817        1
885        1
605        1
471        1
691        1
543        1
97         1
143        1
919        1
10         1
-26        1
148        1
84         1
219        1
704        1
-43        1
145        1
Name: diag_1, dtype: int64
250     11862
428      6517
276      6513
427      4919
401      3613
496      3233
599      3225
403      2781
414      2574
411      2495
707      1922
585      1830
584      1631
491      1513
285      1481
780      1446
425      1411
682      1391
486      1348
518      1326
424      1051
413      1006
493       857
305       675
786       631
280       591
998       551
410       535
511       506
785       501
38        464
996       441
571       408
-45       403
272       401
197       399
162       398
440       394
577       393
295       393
560       389
788       374
41        372
997       369
578       340
453       340
574       337
789       336
648       331
402       327
198       315
799       306
287       301
426       293
303       282
530       276
70        263
-42       261
278       261
438       251
730       239
591       229
790       220
342       219
492       216
196       209
787       199
404       196
536       195
112       193
535       191
8         190
507       185
434       184
202       178
396       178
784       176
733       175
569       171
263       168
304       167
-85       166
284       166
710       163
515       157
296       155
294       153
-58       146
433       146
458       143
724       141
244       141
300       141
562       140
348       138
722       134
590       131
-43       129
728       125
715       120
781       118
593       117
340       114
135       113
-878      112
995       112
204       111
-885      110
286       110
153       106
-888      106
482       105
466       105
415       105
444       104
331       103
412       102
-10       101
-15       100
558        94
416        94
292        94
242        93
567        91
729        90
435        88
203        88
719        88
42         84
576        83
157        83
731        79
572        79
581        78
564        78
592        77
-54        77
443        76
357        76
553        75
311        75
805        74
288        73
293        72
782        72
456        72
291        71
437        69
255        67
-12        66
568        65
397        65
344        65
595        64
-62        64
721        62
301        61
277        60
575        60
596        58
794        57
205        57
723        57
211        53
465        52
820        52
459        51
-849       51
290        49
490        49
309        48
189        48
282        47
625        46
512        46
807        46
337        46
808        46
552        46
154        45
573        44
531        44
218        44
711        43
345        43
332        43
253        42
289        41
873        40
441        40
398        39
681        39
-49        39
557        38
714        37
481        37
600        37
-932       36
327        36
473        35
812        35
349        35
999        34
-942       34
155        33
275        33
150        33
618        33
451        32
53         31
455        31
429        31
362        30
519        30
-63        29
516        29
478        29
446        29
537        28
620        28
850        27
-64        27
642        27
174        27
532        26
447        26
358        26
274        26
626        26
79         25
802        25
94         25
726        25
185        25
924        24
420        24
312        24
738        24
436        24
-935       24
151        24
920        23
727        22
680        22
616        22
813        22
783        22
611        22
368        22
566        21
138        21
-947       21
386        21
394        21
432        21
252        21
614        20
283        20
583        20
-884       20
601        20
346        20
-879       20
421        20
-880       19
617        19
555        19
821        19
200        19
281        18
716        18
201        18
487        18
860        18
736        18
-65        18
556        18
319        18
753        17
824        17
298        17
238        16
156        16
746        16
261        16
333        16
423        16
442        16
958        15
431        15
338        15
550        15
-928       15
840        14
696        14
183        14
745        14
-72        13
199        13
852        13
262        13
359        13
152        13
570        13
462        13
-939       13
607        12
627        12
792        12
718        12
514        12
756        12
494        12
823        12
540        12
378        12
191        12
-944       11
816        11
737        11
382        11
241        11
40         11
-46        11
279        11
335        11
510        11
-44        11
959        11
356        11
233        11
693        11
307        11
251        10
905        10
586        10
-950       10
461        10
260        10
608        10
517        10
706        10
354        10
317        10
54         10
188        10
-09        10
717        10
314        10
867        10
485        10
709         9
324         9
861         9
-934        9
825         9
-57         9
579         9
117         9
741         9
881         9
34          8
-17         8
565         8
836         8
380         8
-930        8
750         8
705         8
208         8
533         8
365         8
923         8
273         8
845         8
621         8
883         8
220         8
-812        8
-70         7
172         7
322         7
922         7
-936        7
619         7
646         7
266         7
594         7
-08         7
758         7
892         7
214         7
457         7
299         7
528         7
452         7
110         7
796         7
882         7
430         6
336         6
713         6
791         6
-917        6
701         6
910         6
934         6
684         6
9           6
524         6
686         6
136         6
-927        6
712         6
297         6
508         6
227         6
454         6
847         6
694         6
369         6
588         5
685         5
-937        5
759         5
647         5
500         5
698         5
323         5
521         5
513         5
604         5
310         5
644         5
343         5
747         5
868         5
495         5
864         5
623         5
480         5
692         5
969         5
793         5
-66         5
225         5
389         5
891         5
725         4
844         4
258         4
246         4
826         4
810         4
320         4
907         4
501         4
-881        4
372         4
921         4
851         4
245         4
306         4
909         4
652         4
522         4
664         4
31          4
989         4
822         4
-02         4
-858        4
360         4
806         4
598         4
831         4
527         4
-933        4
373         3
542         3
645         3
27          3
470         3
131         3
919         3
991         3
395         3
837         3
870         3
-905        3
865         3
-906        3
-887        3
659         3
945         3
355         3
-870        3
-924        3
751         3
972         3
383         3
351         3
-931        3
477         3
377         3
-23         3
405         3
933         3
308         3
-816        3
193         3
842         3
217         3
862         3
-14         3
484         3
239         3
11          3
656         3
603         3
422         3
742         3
376         3
872         2
341         2
795         2
75          2
472         2
691         2
448         2
814         2
-16         2
634         2
-941        2
-53         2
853         2
-814        2
352         2
171         2
474         2
869         2
967         2
663         2
-18         2
622         2
-853        2
379         2
226         2
649         2
866         2
797         2
141         2
483         2
602         2
-821        2
464         2
228         2
543         2
269         2
215         2
-916        2
-55         2
918         2
661         2
366         2
463         2
-86         2
534         2
179         2
78          2
906         2
801         2
911         2
992         2
654         2
-11         2
965         2
381         2
815         2
259         2
952         2
913         2
641         2
610         2
755         2
695         2
-819        2
240         2
-900        1
140         1
703         1
-50         1
748         1
529         1
912         1
7           1
114         1
800         1
-968        1
734         1
917         1
974         1
665         1
-61         1
-929        1
975         1
364         1
350         1
353         1
-60         1
863         1
962         1
963         1
460         1
980         1
871         1
947         1
832         1
702         1
173         1
475         1
506         1
123         1
879         1
130         1
347         1
-25         1
893         1
948         1
212         1
-883        1
-918        1
833         1
670         1
164         1
-817        1
163         1
520         1
-818        1
955         1
182         1
195         1
-854        1
145         1
523         1
658         1
388         1
683         1
-890        1
916         1
137         1
99          1
977         1
-919        1
192         1
96          1
374         1
66          1
-850        1
-829        1
325         1
-69         1
994         1
268         1
270         1
754         1
843         1
271         1
990         1
942         1
927         1
987         1
894         1
811         1
846         1
256         1
-868        1
88          1
223         1
316         1
615         1
-826        1
318         1
-915        1
180         1
580         1
232         1
115         1
-13         1
302         1
-980        1
880         1
944         1
-813        1
884         1
908         1
915         1
35          1
5           1
46          1
186         1
968         1
-938        1
52          1
-882        1
-945        1
953         1
Name: diag_2, dtype: int64
250       16695
401        8089
276        5097
428        4491
427        3865
414        3567
496        2552
403        2322
585        1949
272        1910
599        1906
-45        1372
707        1342
780        1310
285        1175
425        1118
424        1034
584         941
305         904
682         861
518         831
41          711
493         675
278         670
530         606
786         573
491         565
486         552
244         524
-58         498
411         389
280         388
287         385
197         380
785         377
511         374
357         374
402         370
787         352
788         336
412         334
593         329
-15         328
413         324
998         312
294         308
571         307
438         307
560         302
799         301
295         298
997         290
995         288
789         284
535         283
458         281
996         275
70          273
426         270
536         265
263         248
578         242
-42         238
300         236
198         233
-10         233
784         230
396         222
440         216
-849        213
311         210
296         206
410         206
715         205
112         204

In [47]:
df[diag_cols] = df[diag_cols].astype(float)

# diagnosis grouping
for col in diag_cols:
    df['temp']=np.nan
    
    condition = df[col]==250
    df.loc[condition,'temp']='Diabetes'
    
    condition = (df[col]>=390) & (df[col]<=458) | (df[col]==785)
    df.loc[condition,'temp']='Circulatory'
    
    condition = (df[col]>=460) & (df[col]<=519) | (df[col]==786)
    df.loc[condition,'temp']='Respiratory'
    
    condition = (df[col]>=520) & (df[col]<=579) | (df[col]==787)
    df.loc[condition,'temp']='Digestive'
    
    condition = (df[col]>=580) & (df[col]<=629) | (df[col]==788)
    df.loc[condition,'temp']='Genitourinary'
    
    condition = (df[col]>=800) & (df[col]<=999)
    df.loc[condition,'temp']='Injury'
    
    condition = (df[col]>=710) & (df[col]<=739)
    df.loc[condition,'temp']='Muscoloskeletal'
    
    condition = (df[col]>=140) & (df[col]<=239)
    df.loc[condition,'temp']='Neoplasms'
    
    condition = df[col]==0
    df.loc[condition,col]='?'
    df['temp']=df['temp'].fillna('Others')
    condition = df['temp']=='0'
    df.loc[condition,'temp']=np.nan
    df[col]=df['temp']
    df.drop('temp',axis=1,inplace=True)
    
df.dropna(inplace=True)

In [48]:
df['age']=df['age'].replace({'[0-10)':'child','[10-20)':'child','[20-30)':'adult','[30-40)':'adult','[40-50)':'adult','[50-60)':'adult'
                   ,'[60-70)':'Seniors','[70-80)':'Seniors','[80-90)':'Seniors','[90-100)':'Seniors'})

In [49]:
df.head()

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
1,Caucasian,Female,child,3,59,0,18,0,0,0,Others,Diabetes,Others,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,adult,2,11,5,13,2,0,1,Others,Diabetes,Others,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,adult,2,44,1,16,0,0,0,Others,Diabetes,Circulatory,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,Caucasian,Male,adult,1,51,0,8,0,0,0,Neoplasms,Neoplasms,Diabetes,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,Caucasian,Male,adult,3,31,6,16,0,0,0,Circulatory,Circulatory,Diabetes,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30

In [50]:
df['A1Cresult'] = df['A1Cresult'].replace({'>7':'Not Normal', '>8':'Not Normal'})

In [51]:
set(df['A1Cresult'])

{'None', 'Norm', 'Not Normal'}

In [52]:
df['readmitted'] = df['readmitted'].replace({'<30':'Yes', '>30':'Yes'})

In [54]:
set(df['readmitted'])

{'NO', 'Yes'}

In [55]:
a = df[['diag_1','diag_2','diag_3']]
a[:5]

        diag_1       diag_2       diag_3
1       Others     Diabetes       Others
2       Others     Diabetes       Others
3       Others     Diabetes  Circulatory
4    Neoplasms    Neoplasms     Diabetes
5  Circulatory  Circulatory     Diabetes

In [56]:
b =a.replace({'Circulatory':1,'Others':1,'Respiratory':1,'Digestive':1,'Diabetes':0,'Injury':1,'Genitourinary':1,'Muscoloskeletal':1,'Neoplasms':1})

In [57]:
b['all d']= b['diag_1']*b['diag_2']*b['diag_1']

In [58]:
b[:5]

   diag_1  diag_2  diag_3  all d
1       1       0       1      0
2       1       0       1      0
3       1       0       1      0
4       1       1       0      1
5       1       1       0      1

In [59]:
b['all d'].value_counts()

1    78322
0    19730
Name: all d, dtype: int64

In [61]:
b['all d'].value_counts(True)*100

1    79.878024
0    20.121976
Name: all d, dtype: float64

In [62]:
b['all d'] = b['all d'].replace({1:0,0:1})

In [63]:
b['all d'].value_counts(True)*100

0    79.878024
1    20.121976
Name: all d, dtype: float64

In [ ]:
# 1 => Diabetes + others disease
# 0 => others disease but no diabetes

In [64]:
df = df.drop(['diag_1','diag_2','diag_3'],axis=1)

In [65]:
df['Diabetes'] = b['all d']

In [66]:
df[:5]

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,Diabetes
1,Caucasian,Female,child,3,59,0,18,0,0,0,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,Yes,1
2,AfricanAmerican,Female,adult,2,11,5,13,2,0,1,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,1
3,Caucasian,Male,adult,2,44,1,16,0,0,0,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,1
4,Caucasian,Male,adult,1,51,0,8,0,0,0,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,0
5,Caucasian,Male,adult,3,31,6,16,0,0,0,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,Yes,0

# We should apply SMOOTH

In [67]:
cat_cols = df.select_dtypes(include='object').columns
cat_cols

Index(['race', 'gender', 'age', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [68]:
num_cols = df.select_dtypes(exclude='object').columns
num_cols

Index(['time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'Diabetes'],
      dtype='object')

In [69]:
for i in cat_cols:
  c = pd.crosstab(df['Diabetes'],df[i])
  print(c)
  print('**'*20)

race      AfricanAmerican  Asian  Caucasian  Hispanic  Other
Diabetes
0                   13956    515      61218      1476   1157
1                    4925    110      13861       508    326
****************************************
gender    Female   Male
Diabetes
0          42352  35970
1          10481   9249
****************************************
age       Seniors  adult  child
Diabetes
0           56835  21366    121
1            9698   9622    410
****************************************
max_glu_serum  >200  >300   None  Norm
Diabetes
0              1175   764  74273  2110
1               274   463  18571   422
****************************************
A1Cresult   None  Norm  Not Normal
Diabetes
0          66945  3923        7454
1          14914   931        3885
****************************************
metformin  Down     No  Steady   Up
Diabetes
0           409  63331   13864  718
1           142  15476    3813  299
****************************************
repaglinide  Down     No  Steady  Up
Diabetes
0              42  77073    1133  74
1               3  19456     238  33
****************************************
nateglinide  Down     No  Steady  Up
Diabetes
0               9  77757     538  18
1               2  19604     119   5
****************************************
chlorpropamide  Down     No  Steady  Up
Diabetes
0                  0  78249      67   6
1                  1  19720       9   0
****************************************
glimepiride  Down     No  Steady   Up
Diabetes
0             146  74199    3718  259
1              38  18866     770   56
****************************************
acetohexamide     No  Steady
Diabetes
0              78321       1
1              19730       0
****************************************
glipizide  Down     No  Steady   Up
Diabetes
0           450  68183    9098  591
1            91  17586    1892  161
****************************************
glyburide  Down     No  Steady   Up
Diabetes
0           443  69842    7396  641
1            95  17949    1536  150
****************************************
tolbutamide     No  Steady
Diabetes
0            78303      19
1            19727       3
****************************************
pioglitazone  Down     No  Steady   Up
Diabetes
0               94  72574    5491  163
1               21  18381    1264   64
****************************************
rosiglitazone  Down     No  Steady   Up
Diabetes
0                65  73492    4633  132
1                19  18394    1275   42
****************************************
acarbose  Down     No  Steady  Up
Diabetes
0            3  78075     240   4
1            0  19678      46   6
****************************************
miglitol  Down     No  Steady  Up
Diabetes
0            4  78287      30   1
1            0  19728       1   1
****************************************
troglitazone     No  Steady
Diabetes
0             78319       3
1             19730       0
****************************************
tolazamide     No  Steady  Up
Diabetes
0           78293      28   1
1           19722       8   0
****************************************
examide      No
Diabetes
0         78322
1         19730
****************************************
citoglipton     No
Diabetes
0            78322
1            19730
****************************************
insulin   Down     No  Steady    Up
Diabetes
0         8477  38694   23273  7878
1         3366   7248    6095  3021
****************************************
glyburide-metformin  Down     No  Steady  Up
Diabetes
0                       2  77785     529   6
1                       1  19598     131   0
****************************************
glipizide-metformin     No  Steady
Diabetes
0                    78310      12
1                    19729       1
****************************************
glimepiride-pioglitazone     No  Steady
Diabetes
0                         78322       0
1                         19729       1
****************************************
metformin-rosiglitazone     No
Diabetes
0                        78322
1                        19730
****************************************
metformin-pioglitazone     No  Steady
Diabetes
0                       78322       0
1                       19729       1
****************************************
change       Ch     No
Diabetes
0         34689  43633
1         10589   9141
****************************************
diabetesMed     No    Yes
Diabetes
0            19112  59210
1             3590  16140
****************************************
readmitted     NO    Yes
Diabetes
0           42014  36308
1           10323   9407
****************************************

In [70]:
df = df.replace({'Down':'Yes','Up':'Yes','Steady':'Yes'})

In [71]:
for i in cat_cols:
  c = pd.crosstab(df['Diabetes'],df[i])
  print(c)
  print('**'*20)

race      AfricanAmerican  Asian  Caucasian  Hispanic  Other
Diabetes
0                   13956    515      61218      1476   1157
1                    4925    110      13861       508    326
****************************************
gender    Female   Male
Diabetes
0          42352  35970
1          10481   9249
****************************************
age       Seniors  adult  child
Diabetes
0           56835  21366    121
1            9698   9622    410
****************************************
max_glu_serum  >200  >300   None  Norm
Diabetes
0              1175   764  74273  2110
1               274   463  18571   422
****************************************
A1Cresult   None  Norm  Not Normal
Diabetes
0          66945  3923        7454
1          14914   931        3885
****************************************
metformin     No    Yes
Diabetes
0          63331  14991
1          15476   4254
****************************************
repaglinide     No   Yes
Diabetes
0            77073  1249
1            19456   274
****************************************
nateglinide     No  Yes
Diabetes
0            77757  565
1            19604  126
****************************************
chlorpropamide     No  Yes
Diabetes
0               78249   73
1               19720   10
****************************************
glimepiride     No   Yes
Diabetes
0            74199  4123
1            18866   864
****************************************
acetohexamide     No  Yes
Diabetes
0              78321    1
1              19730    0
****************************************
glipizide     No    Yes
Diabetes
0          68183  10139
1          17586   2144
****************************************
glyburide     No   Yes
Diabetes
0          69842  8480
1          17949  1781
****************************************
tolbutamide     No  Yes
Diabetes
0            78303   19
1            19727    3
****************************************
pioglitazone     No   Yes
Diabetes
0             72574  5748
1             18381  1349
****************************************
rosiglitazone     No   Yes
Diabetes
0              73492  4830
1              18394  1336
****************************************
acarbose     No  Yes
Diabetes
0         78075  247
1         19678   52
****************************************
miglitol     No  Yes
Diabetes
0         78287   35
1         19728    2
****************************************
troglitazone     No  Yes
Diabetes
0             78319    3
1             19730    0
****************************************
tolazamide     No  Yes
Diabetes
0           78293   29
1           19722    8
****************************************
examide      No
Diabetes
0         78322
1         19730
****************************************
citoglipton     No
Diabetes
0            78322
1            19730
****************************************
insulin      No    Yes
Diabetes
0         38694  39628
1          7248  12482
****************************************
glyburide-metformin     No  Yes
Diabetes
0                    77785  537
1                    19598  132
****************************************
glipizide-metformin     No  Yes
Diabetes
0                    78310   12
1                    19729    1
****************************************
glimepiride-pioglitazone     No  Yes
Diabetes
0                         78322    0
1                         19729    1
****************************************
metformin-rosiglitazone     No
Diabetes
0                        78322
1                        19730
****************************************
metformin-pioglitazone     No  Yes
Diabetes
0                       78322    0
1                       19729    1
****************************************
change       Ch     No
Diabetes
0         34689  43633
1         10589   9141
****************************************
diabetesMed     No    Yes
Diabetes
0            19112  59210
1             3590  16140
****************************************
readmitted     NO    Yes
Diabetes
0           42014  36308
1           10323   9407
****************************************

In [72]:
df = df.drop(['acetohexamide','tolbutamide' ,'troglitazone','examide',
'citoglipton','glipizide-metformin',
'glimepiride-pioglitazone','metformin-rosiglitazone',
'metformin-pioglitazone' ],axis=1)

In [73]:
cat_cols = df.select_dtypes(include='object').columns
cat_cols

Index(['race', 'gender', 'age', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'tolazamide', 'insulin', 'glyburide-metformin', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')

In [74]:
for i in cat_cols:
  c = pd.crosstab(df['Diabetes'],df[i])
  print(c)
  print('**'*20)

race      AfricanAmerican  Asian  Caucasian  Hispanic  Other
Diabetes
0                   13956    515      61218      1476   1157
1                    4925    110      13861       508    326
****************************************
gender    Female   Male
Diabetes
0          42352  35970
1          10481   9249
****************************************
age       Seniors  adult  child
Diabetes
0           56835  21366    121
1            9698   9622    410
****************************************
max_glu_serum  >200  >300   None  Norm
Diabetes
0              1175   764  74273  2110
1               274   463  18571   422
****************************************
A1Cresult   None  Norm  Not Normal
Diabetes
0          66945  3923        7454
1          14914   931        3885
****************************************
metformin     No    Yes
Diabetes
0          63331  14991
1          15476   4254
****************************************
repaglinide     No   Yes
Diabetes
0            77073  1249
1            19456   274
****************************************
nateglinide     No  Yes
Diabetes
0            77757  565
1            19604  126
****************************************
chlorpropamide     No  Yes
Diabetes
0               78249   73
1               19720   10
****************************************
glimepiride     No   Yes
Diabetes
0            74199  4123
1            18866   864
****************************************
glipizide     No    Yes
Diabetes
0          68183  10139
1          17586   2144
****************************************
glyburide     No   Yes
Diabetes
0          69842  8480
1          17949  1781
****************************************
pioglitazone     No   Yes
Diabetes
0             72574  5748
1             18381  1349
****************************************
rosiglitazone     No   Yes
Diabetes
0              73492  4830
1              18394  1336
****************************************
acarbose     No  Yes
Diabetes
0         78075  247
1         19678   52
****************************************
miglitol     No  Yes
Diabetes
0         78287   35
1         19728    2
****************************************
tolazamide     No  Yes
Diabetes
0           78293   29
1           19722    8
****************************************
insulin      No    Yes
Diabetes
0         38694  39628
1          7248  12482
****************************************
glyburide-metformin     No  Yes
Diabetes
0                    77785  537
1                    19598  132
****************************************
change       Ch     No
Diabetes
0         34689  43633
1         10589   9141
****************************************
diabetesMed     No    Yes
Diabetes
0            19112  59210
1             3590  16140
****************************************
readmitted     NO    Yes
Diabetes
0           42014  36308
1           10323   9407
****************************************

In [75]:
y = df['Diabetes']
x = df.drop('Diabetes',axis =1 )

In [76]:
x.shape

(98052, 30)

In [77]:
y.shape

(98052,)

In [78]:
x = pd.get_dummies(x,drop_first=True)

In [79]:
x.shape

(98052, 37)

In [80]:
y.value_counts(True)*100

0    79.878024
1    20.121976
Name: Diabetes, dtype: float64

In [81]:
import statsmodels.api as sm
xc = sm.add_constant(x)
model= sm.Logit(y,xc, random_state=3).fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.442354
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                98052
Model:                          Logit   Df Residuals:                    98014
Method:                           MLE   Df Model:                           37
Date:                Mon, 16 Nov 2020   Pseudo R-squ.:                  0.1190
Time:                        13:32:44   Log-Likelihood:                -43374.
converged:                       True   LL-Null:                       -49231.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.5713      0.086      6.639      0.000       0.403       0.740
time_in_hospital            0.0095      0.003      2.768      0.006       0.003       0.016
num_lab_procedures         -0.0010      0.000     -2.017      0.044      -0.002    -2.8e-05
num_procedures             -0.0827      0.006    -13.950      0.000      -0.094      -0.071
num_medications            -0.0207      0.001    -14.320      0.000      -0.023      -0.018
number_outpatient           0.0247      0.007      3.740      0.000       0.012       0.038
number_emergency            0.0380      0.008      4.704      0.000       0.022       0.054
number_inpatient            0.0336      0.007      4.910      0.000       0.020       0.047
number_diagnoses           -0.2844      0.005    -59.923      0.000      -0.294      -0.275
race_Asian                 -0.4230      0.114     -3.708      0.000      -0.647      -0.199
race_Caucasian             -0.1497      0.021     -7.112      0.000      -0.191      -0.108
race_Hispanic              -0.1613      0.059     -2.741      0.006      -0.277      -0.046
race_Other                 -0.1777      0.070     -2.536      0.011      -0.315      -0.040
gender_Male                 0.0353      0.017      2.044      0.041       0.001       0.069
age_adult                   0.7278      0.018     40.526      0.000       0.693       0.763
age_child                   1.9074      0.112     17.042      0.000       1.688       2.127
max_glu_serum_>300          0.8810      0.095      9.265      0.000       0.695       1.067
max_glu_serum_None          0.1508      0.071      2.114      0.034       0.011       0.291
max_glu_serum_Norm         -0.0557      0.090     -0.621      0.535      -0.232       0.120
A1Cresult_Norm              0.0813      0.041      1.999      0.046       0.002       0.161
A1Cresult_Not Normal        0.7287      0.025     29.352      0.000       0.680       0.777
metformin_Yes              -0.0644      0.024     -2.639      0.008      -0.112      -0.017
repaglinide_Yes            -0.0264      0.071     -0.369      0.712      -0.166       0.114
nateglinide_Yes            -0.0768      0.105     -0.733      0.464      -0.282       0.129
chlorpropamide_Yes         -0.5052      0.350     -1.443      0.149      -1.191       0.181
glimepiride_Yes            -0.2950      0.042     -6.944      0.000      -0.378      -0.212
glipizide_Yes              -0.2981      0.030     -9.967      0.000      -0.357      -0.239
glyburide_Yes              -0.2576      0.033     -7.888      0.000      -0.322      -0.194
pioglitazone_Yes           -0.1109      0.035     -3.168      0.002      -0.179      -0.042
rosiglitazone_Yes           0.0128      0.036      0.359      0.720      -0.057       0.083
acarbose_Yes               -0.0456      0.160     -0.285      0.776      -0.360       0.268
miglitol_Yes               -1.3282      0.735     -1.806      0.071      -2.770       0.113
tolazamide_Yes             -0.0088      0.422     -0.021      0.983      -0.836       0.818
insulin_Yes                 0.3720      0.029     13.013      0.000       0.316       0.428
glyburide-metformin_Yes    -0.2080      0.104     -2.000      0.046      -0.412      -0.004
change_No                  -0.3595      0.025    -14.463      0.000      -0.408      -0.311
diabetesMed_Yes             0.0604      0.033      1.847      0.065      -0.004       0.125
readmitted_Yes              0.1472      0.018      8.259      0.000       0.112       0.182
===========================================================================================
"""

In [82]:
from statsmodels.stats.outliers_influence \
  import variance_inflation_factor as vif

pd.DataFrame(  [vif(xc.values, i) for i in range(xc.shape[1])]   ,\
             index=xc.columns, columns=['vif']  )

                                vif
const                    105.153391
time_in_hospital           1.386820
num_lab_procedures         1.271586
num_procedures             1.231799
num_medications            1.656642
number_outpatient          1.035840
number_emergency           1.097064
number_inpatient           1.161629
number_diagnoses           1.164894
race_Asian                 1.029428
race_Caucasian             1.227842
race_Hispanic              1.087524
race_Other                 1.066226
gender_Male                1.017791
age_adult                  1.099671
age_child                  1.029458
max_glu_serum_>300         1.829276
max_glu_serum_None         3.531034
max_glu_serum_Norm         2.685143
A1Cresult_Norm             1.037838
A1Cresult_Not Normal       1.099886
metformin_Yes              1.371802
repaglinide_Yes            1.035477
nateglinide_Yes            1.015165
chlorpropamide_Yes         1.005163
glimepiride_Yes            1.127221
glipizide_Yes              1.316476
glyburide_Yes              1.328304
pioglitazone_Yes           1.124871
rosiglitazone_Yes          1.106074
acarbose_Yes               1.006465
miglitol_Yes               1.001339
tolazamide_Yes             1.002127
insulin_Yes                2.770382
glyburide-metformin_Yes    1.017341
change_No                  2.254569
diabetesMed_Yes            2.390994
readmitted_Yes             1.069660

In [83]:
cols=list(xc.columns)
while len(cols)>1:
    x_1= xc[cols]
    model=sm.Logit(y,x_1, random_state=3).fit()
    p=model.pvalues
    max_p= max(p)
    feature_maxp= p.idxmax()
    
    if max_p>0.05:
        print('\n')
        print('column removed: ', feature_maxp, 'prob: ', max_p)
        cols.remove(feature_maxp)
    else:
        break
        
cols

Optimization terminated successfully.
         Current function value: 0.442354
         Iterations 7


column removed:  tolazamide_Yes prob:  0.9832687695491801
Optimization terminated successfully.
         Current function value: 0.442354
         Iterations 7


column removed:  acarbose_Yes prob:  0.7758493258149073
Optimization terminated successfully.
         Current function value: 0.442354
         Iterations 7


column removed:  rosiglitazone_Yes prob:  0.7180809642919023
Optimization terminated successfully.
         Current function value: 0.442355
         Iterations 7


column removed:  repaglinide_Yes prob:  0.705302298076918
Optimization terminated successfully.
         Current function value: 0.442356
         Iterations 7


column removed:  max_glu_serum_Norm prob:  0.534467449993082
Optimization terminated successfully.
         Current function value: 0.442358
         Iterations 7


column removed:  nateglinide_Yes prob:  0.4673764398168273
Optimization terminated successfully.
         Current function value: 0.442360
         Iterations 7


column removed:  chlorpropamide_Yes prob:  0.15078836872986465
Optimization terminated successfully.
         Current function value: 0.442372
         Iterations 7


column removed:  diabetesMed_Yes prob:  0.07530016260552239
Optimization terminated successfully.
         Current function value: 0.442388
         Iterations 7


column removed:  miglitol_Yes prob:  0.0705365826345231
Optimization terminated successfully.
         Current function value: 0.442413
         Iterations 6


column removed:  glyburide-metformin_Yes prob:  0.06455246335790737
Optimization terminated successfully.
         Current function value: 0.442431
         Iterations 6

['const',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'number_diagnoses',
 'race_Asian',
 'race_Caucasian',
 'race_Hispanic',
 'race_Other',
 'gender_Male',
 'age_adult',
 'age_child',
 'max_glu_serum_>300',
 'max_glu_serum_None',
 'A1Cresult_Norm',
 'A1Cresult_Not Normal',
 'metformin_Yes',
 'glimepiride_Yes',
 'glipizide_Yes',
 'glyburide_Yes',
 'pioglitazone_Yes',
 'insulin_Yes',
 'change_No',
 'readmitted_Yes']

In [84]:
cols

['const',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'number_diagnoses',
 'race_Asian',
 'race_Caucasian',
 'race_Hispanic',
 'race_Other',
 'gender_Male',
 'age_adult',
 'age_child',
 'max_glu_serum_>300',
 'max_glu_serum_None',
 'A1Cresult_Norm',
 'A1Cresult_Not Normal',
 'metformin_Yes',
 'glimepiride_Yes',
 'glipizide_Yes',
 'glyburide_Yes',
 'pioglitazone_Yes',
 'insulin_Yes',
 'change_No',
 'readmitted_Yes']

In [85]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                98052
Model:                          Logit   Df Residuals:                    98024
Method:                           MLE   Df Model:                           27
Date:                Mon, 16 Nov 2020   Pseudo R-squ.:                  0.1188
Time:                        13:33:32   Log-Likelihood:                -43381.
converged:                       True   LL-Null:                       -49231.
Covariance Type:            nonrobust   LLR p-value:                     0.000
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    0.5511      0.064      8.559      0.000       0.425       0.677
time_in_hospital         0.0094      0.003      2.733      0.006       0.003       0.016
num_lab_procedures      -0.0010      0.000     -1.999      0.046      -0.002   -1.92e-05
num_procedures          -0.0827      0.006    -13.966      0.000      -0.094      -0.071
num_medications         -0.0206      0.001    -14.314      0.000      -0.023      -0.018
number_outpatient        0.0251      0.007      3.788      0.000       0.012       0.038
number_emergency         0.0379      0.008      4.700      0.000       0.022       0.054
number_inpatient         0.0341      0.007      4.984      0.000       0.021       0.048
number_diagnoses        -0.2843      0.005    -59.978      0.000      -0.294      -0.275
race_Asian              -0.4252      0.114     -3.729      0.000      -0.649      -0.202
race_Caucasian          -0.1499      0.021     -7.129      0.000      -0.191      -0.109
race_Hispanic           -0.1618      0.059     -2.750      0.006      -0.277      -0.046
race_Other              -0.1794      0.070     -2.562      0.010      -0.317      -0.042
gender_Male              0.0350      0.017      2.022      0.043       0.001       0.069
age_adult                0.7286      0.018     40.636      0.000       0.693       0.764
age_child                1.9115      0.112     17.090      0.000       1.692       2.131
max_glu_serum_>300       0.9147      0.078     11.776      0.000       0.762       1.067
max_glu_serum_None       0.1832      0.045      4.037      0.000       0.094       0.272
A1Cresult_Norm           0.0809      0.041      1.990      0.047       0.001       0.161
A1Cresult_Not Normal     0.7286      0.025     29.367      0.000       0.680       0.777
metformin_Yes           -0.0477      0.023     -2.053      0.040      -0.093      -0.002
glimepiride_Yes         -0.2790      0.042     -6.673      0.000      -0.361      -0.197
glipizide_Yes           -0.2778      0.028     -9.757      0.000      -0.334      -0.222
glyburide_Yes           -0.2363      0.031     -7.607      0.000      -0.297      -0.175
pioglitazone_Yes        -0.1040      0.034     -3.037      0.002      -0.171      -0.037
insulin_Yes              0.4072      0.022     18.402      0.000       0.364       0.451
change_No               -0.3547      0.024    -14.748      0.000      -0.402      -0.308
readmitted_Yes           0.1481      0.018      8.320      0.000       0.113       0.183
========================================================================================
"""

In [86]:
pd.DataFrame(model.params).reset_index().rename({'index':'Columns',0:'Coefficient'},axis=1)

                 Columns  Coefficient
0                  const     0.551075
1       time_in_hospital     0.009405
2     num_lab_procedures    -0.000980
3         num_procedures    -0.082718
4        num_medications    -0.020616
5      number_outpatient     0.025055
6       number_emergency     0.037925
7       number_inpatient     0.034094
8       number_diagnoses    -0.284346
9             race_Asian    -0.425212
10        race_Caucasian    -0.149943
11         race_Hispanic    -0.161832
12            race_Other    -0.179436
13           gender_Male     0.034957
14             age_adult     0.728589
15             age_child     1.911487
16    max_glu_serum_>300     0.914679
17    max_glu_serum_None     0.183244
18        A1Cresult_Norm     0.080933
19  A1Cresult_Not Normal     0.728599
20         metformin_Yes    -0.047662
21       glimepiride_Yes    -0.279044
22         glipizide_Yes    -0.277805
23         glyburide_Yes    -0.236256
24      pioglitazone_Yes    -0.104045
25           insulin_Yes     0.407196
26             change_No    -0.354743
27        readmitted_Yes     0.148085

# For Stats

# With VIF and BackWard elimination the selected columns are:

In [87]:
col_sel_1 = set(model.params[1:].index)
col_sel_1

{'A1Cresult_Norm',
 'A1Cresult_Not Normal',
 'age_adult',
 'age_child',
 'change_No',
 'gender_Male',
 'glimepiride_Yes',
 'glipizide_Yes',
 'glyburide_Yes',
 'insulin_Yes',
 'max_glu_serum_>300',
 'max_glu_serum_None',
 'metformin_Yes',
 'num_lab_procedures',
 'num_medications',
 'num_procedures',
 'number_diagnoses',
 'number_emergency',
 'number_inpatient',
 'number_outpatient',
 'pioglitazone_Yes',
 'race_Asian',
 'race_Caucasian',
 'race_Hispanic',
 'race_Other',
 'readmitted_Yes',
 'time_in_hospital'}

In [88]:
Total_cols = set(x.columns)
len(Total_cols)

37

In [89]:
len(col_sel_1)

27

In [90]:
un1 = Total_cols-col_sel_1 
un1             # Unselected columns

{'acarbose_Yes',
 'chlorpropamide_Yes',
 'diabetesMed_Yes',
 'glyburide-metformin_Yes',
 'max_glu_serum_Norm',
 'miglitol_Yes',
 'nateglinide_Yes',
 'repaglinide_Yes',
 'rosiglitazone_Yes',
 'tolazamide_Yes'}

# For ML models

# full grown DT

In [91]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=0)
dt.fit(x,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [92]:
dtf =pd.DataFrame({'Features':x.columns,'importance':dt.feature_importances_*100}).sort_values('importance',ascending=False)
dtf = dtf.reset_index().drop('index',axis=1)
dtf

                   Features  importance
0        num_lab_procedures   19.461384
1           num_medications   15.390974
2          time_in_hospital   11.333017
3          number_diagnoses    8.783469
4            num_procedures    5.632232
5          number_inpatient    5.183338
6               gender_Male    3.322021
7         number_outpatient    3.268165
8                 age_adult    2.702272
9            readmitted_Yes    2.473046
10         number_emergency    2.470213
11           race_Caucasian    2.205367
12            metformin_Yes    1.670143
13                change_No    1.590705
14              insulin_Yes    1.498556
15            glipizide_Yes    1.496163
16            glyburide_Yes    1.358185
17         pioglitazone_Yes    1.224018
18     A1Cresult_Not Normal    1.160153
19          glimepiride_Yes    1.021995
20        rosiglitazone_Yes    1.021083
21           A1Cresult_Norm    0.872971
22          diabetesMed_Yes    0.685006
23                age_child    0.599604
24       max_glu_serum_None    0.572269
25            race_Hispanic    0.562403
26       max_glu_serum_>300    0.455480
27               race_Other    0.443328
28          repaglinide_Yes    0.403557
29       max_glu_serum_Norm    0.326406
30  glyburide-metformin_Yes    0.237934
31          nateglinide_Yes    0.224771
32               race_Asian    0.196891
33             acarbose_Yes    0.091969
34       chlorpropamide_Yes    0.045640
35           tolazamide_Yes    0.012897
36             miglitol_Yes    0.002379

In [93]:
dtf['importance'][:21].sum() # ~ 95%

94.26649654010468

In [94]:
col_sel_3 = set(dtf.iloc[:21,]['Features'])
col_sel_3

{'A1Cresult_Not Normal',
 'age_adult',
 'change_No',
 'gender_Male',
 'glimepiride_Yes',
 'glipizide_Yes',
 'glyburide_Yes',
 'insulin_Yes',
 'metformin_Yes',
 'num_lab_procedures',
 'num_medications',
 'num_procedures',
 'number_diagnoses',
 'number_emergency',
 'number_inpatient',
 'number_outpatient',
 'pioglitazone_Yes',
 'race_Caucasian',
 'readmitted_Yes',
 'rosiglitazone_Yes',
 'time_in_hospital'}

In [95]:
col_sel_1-col_sel_3

{'A1Cresult_Norm',
 'age_child',
 'max_glu_serum_>300',
 'max_glu_serum_None',
 'race_Asian',
 'race_Hispanic',
 'race_Other'}

In [96]:
col_sel_3-col_sel_1

{'rosiglitazone_Yes'}

In [97]:
a=col_sel_1.union(col_sel_3)
a

{'A1Cresult_Norm',
 'A1Cresult_Not Normal',
 'age_adult',
 'age_child',
 'change_No',
 'gender_Male',
 'glimepiride_Yes',
 'glipizide_Yes',
 'glyburide_Yes',
 'insulin_Yes',
 'max_glu_serum_>300',
 'max_glu_serum_None',
 'metformin_Yes',
 'num_lab_procedures',
 'num_medications',
 'num_procedures',
 'number_diagnoses',
 'number_emergency',
 'number_inpatient',
 'number_outpatient',
 'pioglitazone_Yes',
 'race_Asian',
 'race_Caucasian',
 'race_Hispanic',
 'race_Other',
 'readmitted_Yes',
 'rosiglitazone_Yes',
 'time_in_hospital'}

In [98]:
len(a)

28

In [99]:
final_selection = list(a)

In [100]:
final_selection

['num_lab_procedures',
 'glimepiride_Yes',
 'max_glu_serum_>300',
 'glyburide_Yes',
 'insulin_Yes',
 'rosiglitazone_Yes',
 'number_emergency',
 'age_adult',
 'number_diagnoses',
 'A1Cresult_Norm',
 'race_Hispanic',
 'num_medications',
 'max_glu_serum_None',
 'metformin_Yes',
 'A1Cresult_Not Normal',
 'race_Asian',
 'age_child',
 'race_Other',
 'readmitted_Yes',
 'num_procedures',
 'number_outpatient',
 'time_in_hospital',
 'number_inpatient',
 'race_Caucasian',
 'glipizide_Yes',
 'gender_Male',
 'pioglitazone_Yes',
 'change_No']

In [101]:
len(final_selection)

28

In [102]:
x[final_selection][:4]

,num_lab_procedures,glimepiride_Yes,max_glu_serum_>300,glyburide_Yes,insulin_Yes,rosiglitazone_Yes,number_emergency,age_adult,number_diagnoses,A1Cresult_Norm,race_Hispanic,num_medications,max_glu_serum_None,metformin_Yes,A1Cresult_Not Normal,race_Asian,age_child,race_Other,readmitted_Yes,num_procedures,number_outpatient,time_in_hospital,number_inpatient,race_Caucasian,glipizide_Yes,gender_Male,pioglitazone_Yes,change_No
1,59,0,0,0,1,0,0,0,9,0,0,18,1,0,0,0,1,0,1,0,0,3,0,1,0,0,0,0
2,11,0,0,0,0,0,0,1,6,0,0,13,1,0,0,0,0,0,0,5,2,2,1,0,1,0,0,1
3,44,0,0,0,1,0,0,1,7,0,0,16,1,0,0,0,0,0,0,1,0,2,0,1,0,1,0,0
4,51,0,0,0,1,0,0,1,5,0,0,8,1,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0

In [103]:
x1 = x[final_selection]

In [104]:
x1.to_csv('x1_di.csv')
y.to_csv('y1_di.csv')

# We will modify if needed